### ISSUE TITLE
Issues with time/date not correctly using HH:MM dd.mm. (with dot)

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.flot#41]
Hi,
it is not possible to set timedate to "Hh:MM dd.mm." (with the dot at the end marking dot after month.
This case is simply missing (and rendered as HH:MM dd.mm (without the dot at the end of month)

Also I would prefer the times in local time, not utc. There is a commented line timzone=browser. If this is set (not commented anymore) times are great.
You can see this with "7 days", I get Midnight and Midday as vertical lines in the graph. But the
lines are at (berlin summertime) on 02:00 and 14:00, which makes reading the graph as daily a bit akward. Lines at 00:00 and 12:00 look better.
Thank You!

**Comment by harvey637** [comment]
missing dot at end of month is around chart.js line 432

**Comment by harvey637** [comment]
timezone=browser is in charts.js line 521

**Comment by drtp** [comment]
This issue is still unsolved, although the dot in the simple "dd.mm." time format does work correctly. 

![](https://forum.iobroker.net/assets/uploads/files/1551279629784-2019-02-27_15h24_24.png)

Would love to see that it would work with all other settings containing "mm." as well.

![](https://forum.iobroker.net/assets/uploads/files/1551279652134-2019-02-27_15h28_27.png)
