### ISSUE TITLE
NULL als 'default' führt zu 0

### ISSUE THREAD

**Issue by Whilk-and-Misky** [ioBroker/ioBroker.flot#77]
Gude,

wenn man in den Optionen bei "NULL als" den Wert 'default' auswählt, sollte keine Linie gezeichnet werden, wenn keine Werte vorliegen. Bei mir wird jedoch eine Linie zu 0 gezeichnet.

Ist dieses Verhalten bekannt?

Gruß, Steffen

**Comment by thomas725** [comment]
also bei mir gibt's für das Verhalten bei NULL-Werten 3 Auswahlmöglichkeiten:

* "default" & "ignore null values" -> diese beiden verursachen bei mir einfache "löcher" in den linien, aber es "zieht" leider trotzdem den 0-Wert in den Sichtbaren bereich des Diagrams

* und als drittes noch "use 0 instead of null values" was scheinbar bei mir im moment kontraintuitiv das selbe verhalten zeigt wie die anderen beiden.
